services:
  # 1. Express.js RESTful API Server & Socket.io
  - type: web
    name: rescue-api-server
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.3
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # 2. BullMQ SOS Worker (Xử lý ghép đôi ca cứu hộ chạy ngầm)
  - type: worker
    name: rescue-sos-worker
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm run worker
    envVars:
      - key: NODE_VERSION
        value: 22.22.3
      - key: NODE_ENV
        value: production
